# Generated by Django 4.0.2 on 2022-11-15 07:07

import chat.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('passwordHash', models.CharField(max_length=64)),
                ('salt', models.CharField(max_length=64)),
                ('pvtkeyhash', models.CharField(default=None, max_length=64)),
                ('aesciphertext', models.TextField(max_length=1500)),
                ('aesnonce', models.CharField(max_length=100)),
                ('aestag', models.CharField(max_length=100)),
                ('gpowerkey', models.TextField(max_length=650)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=2000)),
                ('status', models.CharField(choices=[('S', 'Sent'), ('R', 'Received'), ('D', 'Seen')], default='S', max_length=1)),
                ('time', models.BigIntegerField(default=chat.models.timestamp)),
                ('receiver', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='received', to='chat.user')),
                ('sender', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='sent', to='chat.user')),
            ],
        ),
    ]
